"""
Code Generator - Generate C code from quantized models

Creates header files with model weights and inference functions.
"""

from typing import Dict, List, Any
from pathlib import Path
import numpy as np
from datetime import datetime

from .quantizer import QuantizationConfig


class CodeGenerator:
    """
    Generate C code for EIF models.
    
    Generates:
    - model_weights.h: Weight arrays and layer configurations
    - model_config.h: Model metadata and defines
    - model_inference.c: Optional inference function
    """
    
    # C type mappings
    CTYPES = {
        'q15': 'int16_t',
        'q7': 'int8_t',
        'int8': 'int8_t',
        'float': 'float'
    }
    
    def __init__(self, model_name: str = 'model', config: QuantizationConfig = None):
        self.model_name = model_name
        self.config = config or QuantizationConfig()
        self.ctype = self.CTYPES.get(self.config.method, 'int16_t')
        
    def generate(self,
                 layers: List[Dict],
                 weights: Dict[str, Any],
                 output_dir: Path,
                 include_inference: bool = True) -> List[str]:
        """
        Generate C code files.
        
        Args:
            layers: Parsed layer info
            weights: Quantized weights dictionary
            output_dir: Output directory
            include_inference: Generate inference function
            
        Returns:
            List of generated file paths
        """
        output_dir = Path(output_dir)
        files = []
        
        # Generate weights header
        weights_file = output_dir / f"{self.model_name}_weights.h"
        self._generate_weights_header(weights_file, weights)
        files.append(str(weights_file))
        
        # Generate config header
        config_file = output_dir / f"{self.model_name}_config.h"
        self._generate_config_header(config_file, layers, weights)
        files.append(str(config_file))
        
        # Generate inference function
        if include_inference:
            inference_file = output_dir / f"{self.model_name}_inference.c"
            self._generate_inference(inference_file, layers, weights)
            files.append(str(inference_file))
            
        return files
    
    def _generate_weights_header(self, filepath: Path, weights: Dict):
        """Generate weights header file."""
        lines = []
        
        # Header guard and includes
        guard = f"{self.model_name.upper()}_WEIGHTS_H"
        lines.append(f"/**")
        lines.append(f" * @file {filepath.name}")
        lines.append(f" * @brief Model weights for {self.model_name}")
        lines.append(f" * @generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f" * @note Auto-generated by eif_convert. Do not edit.")
        lines.append(f" */")
        lines.append(f"")
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}")
        lines.append(f"")
        lines.append(f"#include <stdint.h>")
        lines.append(f"")
        
        # Generate weight arrays for each layer
        for layer in weights['layers']:
            layer_name = self._sanitize_name(layer['name'])
            
            for i, w in enumerate(layer['weights']):
                weight_name = 'kernel' if i == 0 else 'bias'
                array_name = f"{layer_name}_{weight_name}"
                
                lines.extend(self._generate_array(array_name, w, layer['shifts'][i]))
                lines.append("")
                
            # Per-channel scales if applicable
            if self.config.per_channel and isinstance(layer['scales'][0], np.ndarray):
                scales = layer['scales'][0]
                lines.extend(self._generate_float_array(f"{layer_name}_scales", scales))
                lines.append("")
                
        lines.append(f"#endif // {guard}")
        lines.append("")
        
        filepath.write_text("\n".join(lines))
        
    def _generate_config_header(self, filepath: Path, layers: List, weights: Dict):
        """Generate configuration header file."""
        lines = []
        
        guard = f"{self.model_name.upper()}_CONFIG_H"
        lines.append(f"/**")
        lines.append(f" * @file {filepath.name}")
        lines.append(f" * @brief Model configuration for {self.model_name}")
        lines.append(f" * @generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f" */")
        lines.append(f"")
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}")
        lines.append(f"")
        lines.append(f"#include <stdint.h>")
        lines.append(f'#include "{self.model_name}_weights.h"')
        lines.append(f"")
        
        # Model metadata
        lines.append(f"// Model metadata")
        lines.append(f'#define {self.model_name.upper()}_NAME "{self.model_name}"')
        lines.append(f"#define {self.model_name.upper()}_NUM_LAYERS {len(weights['layers'])}")
        lines.append(f'#define {self.model_name.upper()}_QUANT_FORMAT "{weights["format"]}"')
        
        # Input/output shapes
        first_layer = layers[0] if layers else {}
        last_layer = layers[-1] if layers else {}
        
        input_shape = first_layer.get('input_shape', (None, 28, 28, 1))
        output_shape = last_layer.get('output_shape', (None, 10))
        
        lines.append(f"")
        lines.append(f"// Input shape (excluding batch)")
        if len(input_shape) == 4:
            lines.append(f"#define {self.model_name.upper()}_INPUT_H {input_shape[1] or 0}")
            lines.append(f"#define {self.model_name.upper()}_INPUT_W {input_shape[2] or 0}")
            lines.append(f"#define {self.model_name.upper()}_INPUT_C {input_shape[3] or 0}")
        input_size = np.prod([s for s in input_shape[1:] if s])
        lines.append(f"#define {self.model_name.upper()}_INPUT_SIZE {int(input_size)}")
        
        lines.append(f"")
        lines.append(f"// Output shape")
        output_size = np.prod([s for s in output_shape[1:] if s])
        lines.append(f"#define {self.model_name.upper()}_OUTPUT_SIZE {int(output_size)}")
        
        # Layer configurations
        lines.append(f"")
        lines.append(f"// Layer configurations")
        lines.append(f"typedef struct {{")
        lines.append(f"    const char* name;")
        lines.append(f"    const char* type;")
        lines.append(f"    int input_size;")
        lines.append(f"    int output_size;")
        lines.append(f"}} eif_layer_info_t;")
        lines.append(f"")
        
        lines.append(f"static const eif_layer_info_t {self.model_name}_layers[] = {{")
        for layer in layers:
            in_size = np.prod([s for s in layer['input_shape'][1:] if s])
            out_size = np.prod([s for s in layer['output_shape'][1:] if s])
            lines.append(f'    {{"{layer["name"]}", "{layer["type"]}", {int(in_size)}, {int(out_size)}}},')
        lines.append(f"}};")
        
        lines.append(f"")
        lines.append(f"#endif // {guard}")
        lines.append("")
        
        filepath.write_text("\n".join(lines))
        
    def _generate_inference(self, filepath: Path, layers: List, weights: Dict):
        """Generate inference function."""
        lines = []
        
        lines.append(f"/**")
        lines.append(f" * @file {filepath.name}")
        lines.append(f" * @brief Inference function for {self.model_name}")
        lines.append(f" * @generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f" */")
        lines.append(f"")
        lines.append(f'#include "{self.model_name}_config.h"')
        lines.append(f"#include <string.h>")
        lines.append(f"")
        lines.append(f"// Include EIF headers")
        lines.append(f"#include \"eif_nn.h\"")
        lines.append(f"")
        
        # Buffer declarations
        max_activation_size = self._calculate_max_buffer(layers)
        lines.append(f"// Activation buffers")
        lines.append(f"static {self.ctype} _buffer_a[{max_activation_size}];")
        lines.append(f"static {self.ctype} _buffer_b[{max_activation_size}];")
        lines.append(f"")
        
        # Inference function
        lines.append(f"/**")
        lines.append(f" * Run model inference")
        lines.append(f" * @param input Input data ({self.model_name.upper()}_INPUT_SIZE elements)")
        lines.append(f" * @param output Output buffer ({self.model_name.upper()}_OUTPUT_SIZE elements)")
        lines.append(f" * @return 0 on success")
        lines.append(f" */")
        lines.append(f"int {self.model_name}_inference(const {self.ctype}* input, {self.ctype}* output) {{")
        lines.append(f"    const {self.ctype}* in = input;")
        lines.append(f"    {self.ctype}* out = _buffer_a;")
        lines.append(f"")
        
        # Generate layer calls
        for i, layer in enumerate(weights['layers']):
            layer_name = self._sanitize_name(layer['name'])
            layer_type = layer['type']
            config = layer.get('config', {})
            
            comment = f"    // Layer {i}: {layer['name']} ({layer_type})"
            lines.append(comment)
            
            if layer_type == 'conv2d':
                self._gen_conv2d_call(lines, layer_name, config, i, len(layers))
            elif layer_type == 'dense':
                self._gen_dense_call(lines, layer_name, config, i, len(layers))
            elif layer_type in ['maxpool2d', 'avgpool2d']:
                self._gen_pool_call(lines, layer_name, config, layer_type)
            elif layer_type == 'flatten':
                lines.append(f"    // Flatten: no-op (data layout change only)")
            elif layer_type in ['relu', 'activation']:
                self._gen_activation_call(lines, config.get('activation', 'relu'))
            elif layer_type == 'softmax':
                self._gen_softmax_call(lines, layer)
                
            # Swap buffers
            if i < len(weights['layers']) - 1:
                lines.append(f"    {{ {self.ctype}* tmp = in; in = out; out = (tmp == _buffer_a) ? _buffer_b : _buffer_a; }}")
            lines.append(f"")
        
        # Copy to output
        output_size = self._get_output_size(layers[-1])
        lines.append(f"    // Copy result to output")
        lines.append(f"    memcpy(output, in, {output_size} * sizeof({self.ctype}));")
        lines.append(f"    return 0;")
        lines.append(f"}}")
        lines.append("")
        
        filepath.write_text("\n".join(lines))
        
    def _generate_array(self, name: str, data: np.ndarray, shift: int = 15) -> List[str]:
        """Generate C array from numpy array."""
        lines = []
        flat = data.flatten()
        
        lines.append(f"// Shape: {data.shape}, Shift: {shift}")
        lines.append(f"static const {self.ctype} {name}[{len(flat)}] = {{")
        
        # Format values in rows
        row_size = 12
        for i in range(0, len(flat), row_size):
            row = flat[i:i+row_size]
            row_str = ", ".join(f"{int(v)}" for v in row)
            lines.append(f"    {row_str},")
            
        lines.append(f"}};")
        return lines
    
    def _generate_float_array(self, name: str, data: np.ndarray) -> List[str]:
        """Generate float C array."""
        lines = []
        flat = data.flatten()
        
        lines.append(f"static const float {name}[{len(flat)}] = {{")
        row_size = 8
        for i in range(0, len(flat), row_size):
            row = flat[i:i+row_size]
            row_str = ", ".join(f"{v:.6f}f" for v in row)
            lines.append(f"    {row_str},")
        lines.append(f"}};")
        return lines
    
    def _sanitize_name(self, name: str) -> str:
        """Sanitize layer name for C identifier."""
        return name.replace('/', '_').replace('-', '_').replace('.', '_')
    
    def _calculate_max_buffer(self, layers: List) -> int:
        """Calculate maximum activation buffer size needed."""
        max_size = 0
        for layer in layers:
            for shape in [layer.get('input_shape', ()), layer.get('output_shape', ())]:
                size = np.prod([s for s in shape[1:] if s])
                max_size = max(max_size, int(size))
        return max(max_size, 1024)  # Minimum 1KB
    
    def _get_output_size(self, layer: Dict) -> int:
        """Get output size of a layer."""
        shape = layer.get('output_shape', (None, 10))
        return int(np.prod([s for s in shape[1:] if s]))
    
    def _gen_conv2d_call(self, lines: List[str], name: str, config: Dict, idx: int, total: int):
        """Generate Conv2D layer call."""
        lines.append(f"    eif_conv2d(in, out, {name}_kernel, {name}_bias,")
        lines.append(f"               {config.get('filters', 32)}, "
                    f"{config.get('kernel_size', (3,3))[0]}, "
                    f"{config.get('strides', (1,1))[0]});")
        if config.get('activation', 'linear') != 'linear':
            self._gen_activation_call(lines, config['activation'])
    
    def _gen_dense_call(self, lines: List[str], name: str, config: Dict, idx: int, total: int):
        """Generate Dense layer call."""
        lines.append(f"    eif_dense(in, out, {name}_kernel, {name}_bias, {config.get('units', 10)});")
        if config.get('activation', 'linear') != 'linear':
            self._gen_activation_call(lines, config['activation'])
    
    def _gen_pool_call(self, lines: List[str], name: str, config: Dict, pool_type: str):
        """Generate pooling layer call."""
        pool_size = config.get('pool_size', (2, 2))[0]
        if pool_type == 'maxpool2d':
            lines.append(f"    eif_maxpool2d(in, out, {pool_size});")
        else:
            lines.append(f"    eif_avgpool2d(in, out, {pool_size});")
    
    def _gen_activation_call(self, lines: List[str], activation: str):
        """Generate activation call."""
        if activation == 'relu':
            lines.append(f"    eif_relu(out, out, _current_size);")
        elif activation == 'softmax':
            lines.append(f"    eif_softmax(out, out, _current_size);")
        elif activation == 'sigmoid':
            lines.append(f"    eif_sigmoid(out, out, _current_size);")
        elif activation == 'tanh':
            lines.append(f"    eif_tanh(out, out, _current_size);")
    
    def _gen_softmax_call(self, lines: List[str], layer: Dict):
        """Generate softmax call."""
        size = self._get_output_size(layer)
        lines.append(f"    eif_softmax(in, out, {size});")
