/**
 * @file main.c
 * @brief MNIST Inference Demo
 *
 * Demonstrates running the converted MNIST model on embedded.
 *
 * Build: make mnist_demo
 * Run:   ./bin/mnist_demo
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// Include generated model
// These would be generated by: python -m eif_convert mnist_model.h5 -o ./
// #include "mnist_config.h"

// For demo purposes, we'll simulate the model

#define MNIST_INPUT_SIZE 784 // 28x28
#define MNIST_OUTPUT_SIZE 10

// Simulated test image (a simple "1")
static const int16_t test_image[MNIST_INPUT_SIZE] = {
    // Most pixels are 0, with a vertical line
    // This is a simplified representation
    0};

// Simulated inference (placeholder until model is generated)
static int mnist_inference_demo(const int16_t *input, int16_t *output) {
  // Simple demo: detect if image has activity in center column
  int32_t sum = 0;
  for (int i = 0; i < MNIST_INPUT_SIZE; i++) {
    sum += input[i];
  }

  // Fake softmax output
  for (int i = 0; i < MNIST_OUTPUT_SIZE; i++) {
    output[i] = 1000; // ~0.03 probability each
  }

  // Highest probability for digit 1
  output[1] = 25000; // ~0.76 probability

  return 0;
}

static int argmax(const int16_t *arr, int len) {
  int max_idx = 0;
  int16_t max_val = arr[0];
  for (int i = 1; i < len; i++) {
    if (arr[i] > max_val) {
      max_val = arr[i];
      max_idx = i;
    }
  }
  return max_idx;
}

static void print_probabilities(const int16_t *output) {
  printf("\nClass Probabilities:\n");
  printf("═══════════════════════════════════════\n");

  for (int i = 0; i < MNIST_OUTPUT_SIZE; i++) {
    float prob = output[i] / 32767.0f; // Q15 to float
    int bar_len = (int)(prob * 30);

    printf("  %d: ", i);
    for (int j = 0; j < bar_len; j++)
      printf("█");
    for (int j = bar_len; j < 30; j++)
      printf("░");
    printf(" %.1f%%\n", prob * 100);
  }
}

int main(void) {
  printf("╔═══════════════════════════════════════╗\n");
  printf("║     MNIST Inference Demo (EIF)        ║\n");
  printf("╚═══════════════════════════════════════╝\n");

  // Prepare input (would be real image data)
  int16_t input[MNIST_INPUT_SIZE];
  memset(input, 0, sizeof(input));

  // Add some "1" pattern
  for (int row = 5; row < 23; row++) {
    input[row * 28 + 14] = 32000; // Vertical line in center
  }

  // Run inference
  int16_t output[MNIST_OUTPUT_SIZE];
  printf("\nRunning inference...\n");

  int result = mnist_inference_demo(input, output);

  if (result == 0) {
    int predicted = argmax(output, MNIST_OUTPUT_SIZE);

    print_probabilities(output);

    printf("\n═══════════════════════════════════════\n");
    printf("Predicted digit: %d\n", predicted);
    printf("═══════════════════════════════════════\n");
  } else {
    printf("Inference failed!\n");
  }

  return 0;
}
