[platformio]
src_dir = .

[env:datum_dash_esp8266]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 160000000L
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    bblanchon/ArduinoJson @ ^6.21.2
    knolleary/PubSubClient @ ^2.8
    bodmer/TJpg_Decoder @ ^1.0.8
