name: Flutter App (Container)

on:
  push:
    paths:
      - 'examples/datum_camera_app/**'
      - '.github/workflows/flutter_local.yml'
  pull_request:
    paths:
      - 'examples/datum_camera_app/**'
      - '.github/workflows/flutter_local.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test in Container
        run: |
          echo "Test Hostname: $HOSTNAME"
          docker run --rm \
            --volumes-from $HOSTNAME \
            -w ${{ github.workspace }}/examples/datum_camera_app \
            -e GITHUB_WORKSPACE=${{ github.workspace }} \
            datum-flutter-builder:latest \
            /bin/bash -c "
              echo '📂 Debugging Paths (Volumes From):'
              pwd
              ls -la
              
              git config --global --add safe.directory '*' && \
              flutter pub get && \
              flutter pub run build_runner build --delete-conflicting-outputs && \
              flutter analyze && \
              flutter test && \
              flutter build apk --release
            "
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: datum-app-release-apk
          path: examples/datum_camera_app/build/app/outputs/flutter-apk/app-release.apk
